CREATE TABLE [Personas] (
	[DNI] VARCHAR NOT NULL UNIQUE,
	[Nombre] VARCHAR NOT NULL,
	[Direccion] VARCHAR NOT NULL,
	[Telefono] VARCHAR NOT NULL,
	[Permisos] CHAR NOT NULL DEFAULT '0',
	PRIMARY KEY([DNI])
);
GO

CREATE INDEX [Personas_index_0]
ON [Personas] ([Nombre]);
GO

CREATE TABLE [Usuario] (
	[id_U] TINYINT NOT NULL IDENTITY UNIQUE,
	[Email] VARCHAR NOT NULL UNIQUE,
	[Contraseña] VARCHAR NOT NULL,
	[DNI] VARCHAR NOT NULL UNIQUE,
	PRIMARY KEY([id_U])
);
GO

CREATE TABLE [Cetegoria_Menu] (
	[id_Categoria] TINYINT NOT NULL IDENTITY UNIQUE,
	[Descripcion] VARCHAR NOT NULL UNIQUE,
	PRIMARY KEY([id_Categoria])
);
GO

CREATE TABLE [Menu] (
	[id_Menu] TINYINT NOT NULL IDENTITY UNIQUE,
	[Descripcion] VARCHAR NOT NULL UNIQUE,
	[id_Categoria] TINYINT NOT NULL,
	PRIMARY KEY([id_Menu])
);
GO

CREATE TABLE [Ordenes] (
	[id_Orden] TINYINT NOT NULL IDENTITY UNIQUE,
	[id_Menu] TINYINT NOT NULL,
	[Cantidad] TINYINT NOT NULL,
	PRIMARY KEY([id_Orden])
);
GO

CREATE TABLE [Pedidos] (
	[id_Pedido] TINYINT NOT NULL IDENTITY UNIQUE,
	[id_Mesa] TINYINT NOT NULL,
	[id_U] TINYINT NOT NULL,
	[id_Orden] TINYINT NOT NULL UNIQUE,
	PRIMARY KEY([id_Pedido])
);
GO

CREATE TABLE [Mesas] (
	[id_Mesa] TINYINT NOT NULL IDENTITY UNIQUE,
	[id_Mesero] TINYINT NOT NULL UNIQUE,
	PRIMARY KEY([id_Mesa])
);
GO

CREATE TABLE [Mesero] (
	[id-Mesero] TINYINT NOT NULL IDENTITY UNIQUE,
	[id_U] TINYINT NOT NULL UNIQUE,
	PRIMARY KEY([id-Mesero])
);
GO


ALTER TABLE [Personas]
ADD FOREIGN KEY([DNI])
REFERENCES [Usuario]([DNI])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Mesero]
ADD FOREIGN KEY([id_U])
REFERENCES [Usuario]([id_U])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Mesas]
ADD FOREIGN KEY([id_Mesero])
REFERENCES [Mesero]([id-Mesero])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Mesas]
ADD FOREIGN KEY([id_Mesa])
REFERENCES [Pedidos]([id_Mesa])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Ordenes]
ADD FOREIGN KEY([id_Orden])
REFERENCES [Pedidos]([id_Orden])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Usuario]
ADD FOREIGN KEY([id_U])
REFERENCES [Pedidos]([id_U])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Menu]
ADD FOREIGN KEY([id_Menu])
REFERENCES [Ordenes]([id_Menu])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Cetegoria_Menu]
ADD FOREIGN KEY([id_Categoria])
REFERENCES [Menu]([id_Categoria])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO